import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Header from '@/component/Header/Header'
import Footer from '@/component/Footer/Footer'

import './globals.scss'
import styles from './layout.module.scss'

const font = Roboto({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  variable: '--main-font',
  style: ['normal']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <div className={styles.container}>
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}

